### ISSUE TITLE
Duplicated code

### ISSUE THREAD

**Issue by ChenhuaYang** [tommy-muehle/go-mnd#26]
### Short summary 
There exists many duplicated code， why not refactoring？It seems that in each checker, the desitination is always a BasicLit, and before find a BasicLit, there are codes duplicated.

**Comment by tommy-muehle** [comment]
Hi @ChenhuaYang, 

you're totally right! 

This linter is mainly the result of trying out the go/analysis API some years ago. Since then I had multiple times in the past the idea/wish to rewrite it completely in a v2 and use a custom analyser like in gosec or similar tools and better CLI support.

But to be honest this project has not my main focus. So don't get me wrong. I will of course fix bugs and false-positives when they pop up. But I've no time for a complete rewrite.

Cheers,
Tommy
