### ISSUE TITLE
Handle digit separator `_`

### ISSUE THREAD

**Issue by benoitmasson** [tommy-muehle/go-mnd#8]
Since [Go 1.13](https://golang.org/doc/go1.13#language), numbers may contain `_` between digits.

It would be nice that when a number is added to the ignored list, all its variants containing `_` be ignored as well: `--ignored-numbers 1000` should match `1000` and  `1_000`.

Currently, we have to specify `--ignored-numbers 1000,1_000` manually.

**Comment by tommy-muehle** [comment]
@benoitmasson 
Thanks for the report. I'll check this asap.

**Comment by tommy-muehle** [comment]
Hi @benoitmasson,

I have made two attempts to implement this so far. Because I got your point. But the documentation isn't really helpful here and I also couldn't find a package which does a conversion of the numbers. Because for numbers like 1000 it seems easy on the first glance. But for example you can write `1234567890` like `1234_567_890` or `1_234_567_890` but also like this `1_234_567_89_0`.  So I need to generate this combinations in a general way to find every time all occurrences when you give me for example the number `1234567890` to ignore.

But unfortunately I couldn't find one so far. So that I'm stuck here and didn't have the time to go further here.

**Comment by benoitmasson** [comment]
Generating all combinations can be done, as follows using recursion for example:
```go
func generateNumberVariants(num int) []string {
	sign := ""
	if num < 0 {
		sign = "-"
		num = -num
	}

	return generateNumberVariantsAux(strconv.Itoa(num), sign)
}

func generateNumberVariantsAux(num, prefix string) []string {
	if len(num) <= 1 {
		return []string{prefix + num}
	}

	variantsWithoutUnderscore := generateNumberVariantsAux(num[1:], prefix+num[0:1])
	variantsWithUnderscore := generateNumberVariantsAux(num[1:], prefix+num[0:1]+"_")
	return append(
		variantsWithoutUnderscore,
		variantsWithUnderscore...,
	)
}
```
but it is computationally heavy, and generates a lot of elements if the input number is large (_2^log(n)_ variants for _n_).

Wouldn't it be easier to do the opposite, i.e., for every magic number found in the code, normalize it by removing `_`'s and check whether this normalized form should be ignored?

**Comment by tommy-muehle** [comment]
@benoitmasson That's totally right. Thanks for putting me on the right path! It's so easy sometimes 🙈
